project:
  type: website

website:
  title: "Attento"
  sidebar: 
    style: "docked"
    search: true
    contents: 
      - section: "The project"
        contents: 
          - index.qmd
          - team.qmd
     
  
  page-footer: "Copyright 2024, Team Attento"
  cookie-consent: true

format:
  html:
    theme: 
      light: cosmo
      dark: slate
    css: styles.css
    toc: true

editor: visual

