project:
  type: website

website:
  title: "Attento"
  page-navigation: true
  back-to-top-navigation: true
  sidebar: 
    style: "docked"
    logo: fig/logo2.jpeg
    search: true
    contents: 
      - section: "The project"
        contents: 
          - index.qmd
          - team.qmd
      - section: "Functional motor disorders"
        contents: 
          - FMD_general.qmd
          - FMD_assessment.qmd
          - FMD_treatment.qmd
      - section: "Focus of attention"
        contents:
          - Attention_general.qmd
      
     
  
  page-footer: "Copyright 2024, Team Attento"
  cookie-consent: true

format:
  html:
    theme: 
      light: cosmo
      dark: slate
    css: styles.css
    toc: true

editor: visual

