project:
  type: website

website:
  title: "Attento"
  page-navigation: true
  back-to-top-navigation: true
  sidebar: 
    style: "docked"
    logo: fig/logo2.jpeg
    search: true
    contents: 
      - section: "The project"
        contents: 
          - index.qmd
          - team.qmd
      - section: "Functional motor disorders"
        contents: 
          - FMD/FMD_general.qmd
          - FMD/FMD_assessment.qmd
          - FMD/FMD_treatment.qmd
      - section: "Focus of attention"
        contents:
          - FOCUS/Attention_intro.qmd
          - FOCUS/Attention_sport.qmd
          - FOCUS/Attention_PD.qmd
          - FOCUS/Attention_stroke.qmd
          - FOCUS/Attention_msk.qmd
      - section: "Privacy policy"
        contents: privacy_policy.qmd
      
  page-footer: "Copyright 2025, Team Attento"
  cookie-consent: true

format:
  html:
    theme: 
      light: cosmo
      dark: slate
    css: styles.css
    toc: true

editor: visual

