---
title: "Team"
---

## Research team

[Dr Michela Bassolino](https://www.hevs.ch/en/collaborateurs/bassolino-24430)

-   PI
-   HES-SO Valais-Wallis, Switzerland

Marie Bonjour, MSc

-   Scientific collaborator

[Dr Gaia Risso](https://www.linkedin.com/in/gaia-risso-640752145/?originalSubdomain=ch)

-   Post-doc
-   HES-SO Valais-Wallis, Switzerland

[Ayla Gay, MSc](https://www.hevs.ch/en/collaborateurs/gay-207340)

-   PhD candidate
-   HES-SO Valais-Wallis, Switzerland

[Dr Martin Sattelmayer](https://www.hevs.ch/de/collaborateurs/sattelmayer-5246)

-   Co-applicant
-   School of Health Sciences, HES-SO Valais-Wallis, Leukerbad, Valais-Wallis, Switzerland

## Student projects

Yasmina Häberli & Mattia Innocenti

-   Bachelor thesis

-   graduated 2025 at HES-SO Valais-Wallis

Astrid Jule & Marlena Gerber

-   Bachelor thesis

-   graduated 2025 at HES-SO Valais-Wallis

Vaucher Eliot & Willemin Noé

-   Bachelor thesis

-   graduated 2025 at HES-SO Valais-Wallis

Camille Jung & Diane Meyer

-   Bachelor thesis

-   graduated 2025 at HES-SO Valais-Wallis

Marie Bonjour, MSc

-   Master thesis

-   graduated 2024 at Berner Fachhochschule

Gaël Christen, BSc & Maël Krieg, BSc

-   Bachelor thesis

-   graduated 2024 at HES-SO Valais-Wallis

Siri Nyfeller, BSc & Emmanuel Favre Bulle, BSc

-   Bachelor thesis

-   graduated 2023 at HES-SO Valais-Wallis

Marie Balet, BSc & Coralie Chaperon, BSc

-   Bachelor thesis

-   graduated 2023 at HES-SO Valais-Wallis
